category: fixed
summary: Fix the translation of cloud init scripts into base64 encoded strings
pull requests:
  - 126
description: |
  The translation of cloud init scripts into base64 encoded strings has been fixed. Reason was changing a data structure
  while interating over it. 
