FROM rockylinux:8
LABEL maintainer="Manuel Giffels <giffels@gmail.com>"

RUN dnf -y install epel-release && dnf -y install curl && dnf clean all

RUN curl -sL https://rpm.nodesource.com/setup_18.x | bash -

RUN dnf -y update \
    && dnf -y install git \
                      python3.12 \
                      gcc \
                      python3.12-devel \
                      nodejs \
                      glibc-langpack-en \
    && dnf clean all

# Make Python3.12 default
RUN alternatives --set python3 /usr/bin/python3.12

SHELL [ "/bin/bash", "--noprofile", "--norc", "-e", "-o", "pipefail", "-c" ]
