FROM centos:7
LABEL maintainer="Manuel Giffels <giffels@gmail.com>"

RUN yum -y install epel-release centos-release-scl-rh curl && yum clean all
RUN yum --enablerepo=centos-sclo-rh -y install rh-python38 && yum clean all

RUN curl -sL https://rpm.nodesource.com/setup_16.x | bash -

RUN yum -y update \
    && yum -y install git \
                      gcc \
                      nodejs \
    && yum clean all

# Enable rh-python38 from SCL
ENV PATH=/opt/rh/rh-python38/root/usr/local/bin:/opt/rh/rh-python38/root/usr/bin${PATH:+:${PATH}}
ENV LD_LIBRARY_PATH=/opt/rh/rh-python38/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
ENV MANPATH=/opt/rh/rh-python38/root/usr/share/man:$MANPATH
ENV PKG_CONFIG_PATH=/opt/rh/rh-python38/root/usr/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
ENV XDG_DATA_DIRS="/opt/rh/rh-python38/root/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"

SHELL [ "/bin/bash", "--noprofile", "--norc", "-e", "-o", "pipefail", "-c" ]
