FROM rockylinux:8
LABEL maintainer="Manuel Giffels <giffels@gmail.com>"

RUN yum -y install epel-release && yum -y install curl && yum clean all

RUN curl -sL https://rpm.nodesource.com/setup_18.x | bash -

RUN yum -y update \
    && yum -y install git \
                      python39 \
                      gcc \
                      python39-devel \
                      nodejs \
                      glibc-langpack-en \
    && yum clean all

# Make Python3.9 default
RUN alternatives --set python3 /usr/bin/python3.9

SHELL [ "/bin/bash", "--noprofile", "--norc", "-e", "-o", "pipefail", "-c" ]
