FROM quay.io/centos/centos:stream8
LABEL maintainer="Manuel Giffels <giffels@gmail.com>"

RUN curl -sL https://rpm.nodesource.com/setup_18.x | bash -

RUN dnf -y update \
    && dnf -y install git \
                      python39 \
                      gcc-8.5.0-7.el8 \
                      python39-devel \
                      nodejs \
                      glibc-langpack-en \
    && dnf clean all

SHELL [ "/bin/bash", "--noprofile", "--norc", "-e", "-o", "pipefail", "-c" ]
