pipeline:
  - !LinearController
    low_utilisation: 0.90
    high_allocation: 0.90
    rate: 1
  - !Limiter
    minimum: 1
  - !Logger
    name: 'changes'
  - __type__: tardis.resources.poolfactory.create_composite_pool
logging:
  version: 1
  root:
      level: DEBUG
      handlers: [console, file]
  formatters:
    precise:
      format: '%(name)s: %(asctime)s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class : logging.StreamHandler
      formatter: precise
      stream  : ext://sys.stdout
    file:
      class : logging.handlers.RotatingFileHandler
      formatter: precise
      filename: tardis.log
      maxBytes: 10485760
      backupCount: 3
tardis:
  Plugins:
    SqliteRegistry:
      db_file: drone_registry.db
  
  BatchSystem:
    adapter: FakeBatchSystem
    allocation: 1.0
    utilisation: !TardisPeriodicValue
                 period: 3600
                 amplitude: 0.5
                 offset: 0.5
                 phase: 0.
    machine_status: Available
  
  Sites:
    - name: Fake
      adapter: FakeSite
      quota: 8000 # CPU core quota
  
  Fake:
    api_response_delay: !TardisRandomGauss
                        mu: 0.1
                        sigma: 0.01
    resource_boot_time: !TardisRandomGauss
                        mu: 60
                        sigma: 10
    MachineTypes:
      - m1.infinity
    MachineTypeConfiguration:
      m1.infinity:
    MachineMetaData:
      m1.infinity:
        Cores: 8
        Memory: 16
        Disk: 160
