name: Static Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[contrib]
    - name: Lint with flake8
      run: |
        flake8 tardis tests setup.py
    - name: Format with black
      run: |
        black tardis tests setup.py --diff --check
